### ISSUE TITLE
Alpine container

### ISSUE THREAD

**Issue by chinkung** [ajhaydock/BoringNginx#4]
It would be great if you could implement BoringNginx on alpine container for docker.

Alpine is lighter than centos and ubuntu for using with docker.

**Comment by alexhaydock** [comment]
I'll have a look into it and see what I can do. I don't have much experience with the newer container-focused distros like Alpine and Void, but have been meaning to investigate them.

If you have any hints or tips to share about Alpine containers, please do let me know!

**Comment by alexhaydock** [comment]
I've made a start on this with #5, which seems to convert the CentOS container into a working Alpine container.

This seems to have brought the size down from 341MB to about 306MB. Not such a huge difference, but for security purposes I like the idea of basing the container on a more minimal distribution like Alpine anyway.

Unfortunately I've temporarily had to disable the PageSpeed module, as the precompiled PSOL binaries that are required to enable the module do not work properly on a system without glibc and would need patching. This isn't necessary for the container to function properly though and is just a nice addition, so I've gone ahead and turned it off until I can get the patches sorted out.
